AWSTemplateFormatVersion: 2010-09-09
Description: Deploy do Grafana e outras ferramentas no AWS ECS com CloudFormation

Parameters:
  ClusterName:
    Type: String
    Description: Nome do cluster ECS existente
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID da VPC onde os recursos serao provisionados
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Lista de IDs das Subnets para o servico ECS
  GrafanaImage:
    Type: String
    Default: grafana/grafana:latest
    Description: Imagem Docker do Grafana
  Cpu:
    Type: Number
    Description: CPU units para a task
  Memory:
    Type: Number
    Description: Memoria em MiB para a task
  DesiredCount:
    Type: Number
    Description: Numero desejado de instancias da task
  TempoImage:
    Type: String
    Default: grafana/tempo:latest
    Description: Imagem Docker do Tempo
  LokiImage:
    Type: String
    Default: grafana/loki:latest
    Description: Imagem Docker do Loki
  PrometheusImage:
    Type: String
    Default: prom/prometheus:latest
    Description: Imagem Docker do Prometheus
  DomainName:
    Type: String
    Description: Nome de dominio para o registro no Route 53
  HostedZoneId:
    Type: String
    Description: ID da Hosted Zone do Route 53

Resources:
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  GrafanaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/monitoring
      RetentionInDays: 14

  GrafanaServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group para o servico ECS do Grafana
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  GrafanaEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS

  TempoEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS

  LokiEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS

  PrometheusEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS

  EFSMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref GrafanaEFSFileSystem
      SubnetId: !Select [0, !Ref SubnetIds]
      SecurityGroups:
        - !Ref EFSSecurityGroup

  EFSMountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref GrafanaEFSFileSystem
      SubnetId: !Select [1, !Ref SubnetIds]
      SecurityGroups:
        - !Ref EFSSecurityGroup

  EFSMountTarget3:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref TempoEFSFileSystem
      SubnetId: !Select [0, !Ref SubnetIds]
      SecurityGroups:
        - !Ref EFSSecurityGroup

  EFSMountTarget4:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref TempoEFSFileSystem
      SubnetId: !Select [1, !Ref SubnetIds]
      SecurityGroups:
        - !Ref EFSSecurityGroup

  EFSMountTarget5:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref LokiEFSFileSystem
      SubnetId: !Select [0, !Ref SubnetIds]
      SecurityGroups:
        - !Ref EFSSecurityGroup

  EFSMountTarget6:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref LokiEFSFileSystem
      SubnetId: !Select [1, !Ref SubnetIds]
      SecurityGroups:
        - !Ref EFSSecurityGroup

  EFSMountTarget7:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref PrometheusEFSFileSystem
      SubnetId: !Select [0, !Ref SubnetIds]
      SecurityGroups:
        - !Ref EFSSecurityGroup

  EFSMountTarget8:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref PrometheusEFSFileSystem
      SubnetId: !Select [1, !Ref SubnetIds]
      SecurityGroups:
        - !Ref EFSSecurityGroup

  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group para o EFS
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          CidrIp: 0.0.0.0/0

  GrafanaLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub grafana-alb-${AWS::StackName}
      Scheme: internet-facing
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref GrafanaALBSecurityGroup
      Type: application
    DependsOn: GrafanaALBSecurityGroup

  GrafanaALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group para o ALB do Grafana
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  GrafanaTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: tg-grafana-stack
      Protocol: HTTP
      Port: 3000
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-399
    DependsOn: GrafanaLoadBalancer

  TempoTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: tg-tempo-stack
      Protocol: HTTP
      Port: 3200
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-399
    DependsOn: GrafanaLoadBalancer

  LokiTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: tg-loki-stack
      Protocol: HTTP
      Port: 3100
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-399
    DependsOn: GrafanaLoadBalancer

  PrometheusTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: tg-prometheus-stack
      Protocol: HTTP
      Port: 9090
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-399
    DependsOn: GrafanaLoadBalancer

  GrafanaListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref GrafanaLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref GrafanaTargetGroup
    DependsOn: GrafanaTargetGroup

  GrafanaListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref GrafanaListener
      Conditions:
        - Field: path-pattern
          Values: ["/"]
      Actions:
        - Type: forward
          TargetGroupArn: !Ref GrafanaTargetGroup
      Priority: 1

  TempoListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref GrafanaListener
      Conditions:
        - Field: path-pattern
          Values: ["/tempo/*"]
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TempoTargetGroup
      Priority: 2

  LokiListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref GrafanaListener
      Conditions:
        - Field: path-pattern
          Values: ["/loki/*"]
      Actions:
        - Type: forward
          TargetGroupArn: !Ref LokiTargetGroup
      Priority: 3

  PrometheusListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref GrafanaListener
      Conditions:
        - Field: path-pattern
          Values: ["/prometheus/*"]
      Actions:
        - Type: forward
          TargetGroupArn: !Ref PrometheusTargetGroup
      Priority: 4

  GrafanaTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: grafana-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: grafana
          Image: !Ref GrafanaImage
          Essential: true
          PortMappings:
            - ContainerPort: 3000
          MountPoints:
            - SourceVolume: grafana-volume
              ContainerPath: /var/lib/grafana
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/monitoring
              awslogs-region: us-east-2
              awslogs-stream-prefix: grafana
        - Name: loki
          Image: !Ref LokiImage
          Essential: true
          PortMappings:
            - ContainerPort: 3100
          MountPoints:
            - SourceVolume: loki-volume
              ContainerPath: /etc/loki
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/monitoring
              awslogs-region: us-east-2
              awslogs-stream-prefix: loki
        - Name: tempo
          Image: !Ref TempoImage
          Essential: true
          PortMappings:
            - ContainerPort: 3200
          MountPoints:
            - SourceVolume: tempo-volume
              ContainerPath: /etc/tempo
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/monitoring
              awslogs-region: us-east-2
              awslogs-stream-prefix: tempo
        - Name: prometheus
          Image: !Ref PrometheusImage
          Essential: true
          PortMappings:
            - ContainerPort: 9090
          MountPoints:
            - SourceVolume: prometheus-volume
              ContainerPath: /etc/prometheus
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/monitoring
              awslogs-region: us-east-2
              awslogs-stream-prefix: prometheus
      Volumes:
        - Name: grafana-volume
          EFSVolumeConfiguration:
            FilesystemId: !Ref GrafanaEFSFileSystem
            RootDirectory: /
            TransitEncryption: ENABLED
        - Name: loki-volume
          EFSVolumeConfiguration:
            FilesystemId: !Ref LokiEFSFileSystem
            RootDirectory: /
            TransitEncryption: ENABLED
        - Name: tempo-volume
          EFSVolumeConfiguration:
            FilesystemId: !Ref TempoEFSFileSystem
            RootDirectory: /
            TransitEncryption: ENABLED
        - Name: prometheus-volume
          EFSVolumeConfiguration:
            FilesystemId: !Ref PrometheusEFSFileSystem
            RootDirectory: /
            TransitEncryption: ENABLED

  GrafanaService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      ServiceName: grafana-service
      TaskDefinition: !Ref GrafanaTaskDefinition
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !GetAtt GrafanaServiceSecurityGroup.GroupId
          Subnets: !Ref SubnetIds
      LoadBalancers:
        - ContainerName: grafana
          ContainerPort: 3000
          TargetGroupArn: !Ref GrafanaTargetGroup
        - ContainerName: loki
          ContainerPort: 3100
          TargetGroupArn: !Ref LokiTargetGroup
        - ContainerName: tempo
          ContainerPort: 3200
          TargetGroupArn: !Ref TempoTargetGroup
        - ContainerName: prometheus
          ContainerPort: 9090
          TargetGroupArn: !Ref PrometheusTargetGroup
    DependsOn: 
      - GrafanaTaskDefinition
      - GrafanaListener
      - TempoListenerRule
      - LokiListenerRule
      - PrometheusListenerRule

  GrafanaDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: monitoring.dev.gen.com.br
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt GrafanaLoadBalancer.CanonicalHostedZoneID
        DNSName: !GetAtt GrafanaLoadBalancer.DNSName

Outputs:
  GrafanaURL:
    Description: URL do Grafana acessível via Route 53
    Value: monitoring.dev.gen.com.br
