AWSTemplateFormatVersion: 2010-09-09
Description: Deploy do Grafana e outras ferramentas no AWS ECS com CloudFormation

Parameters:
  ClusterName:
    Type: String
    Description: Nome do cluster ECS existente
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID da VPC onde os recursos serao provisionados
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Lista de IDs das Subnets para o servico ECS
  GrafanaImage:
    Type: String
    Default: grafana/grafana:latest
    Description: Imagem Docker do Grafana
  Cpu:
    Type: Number
    Default: 512
    Description: CPU units para a task
  Memory:
    Type: Number
    Default: 1024
    Description: Memoria em MiB para a task
  DesiredCount:
    Type: Number
    Default: 1
    Description: Numero desejado de instancias da task
  TempoImage:
    Type: String
    Default: grafana/tempo:latest
    Description: Imagem Docker do Tempo
  LokiImage:
    Type: String
    Default: grafana/loki:latest
    Description: Imagem Docker do Loki
  PrometheusImage:
    Type: String
    Default: prom/prometheus:latest
    Description: Imagem Docker do Prometheus

Resources:
  GrafanaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/monitoring
      RetentionInDays: 14

  GrafanaServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group para o servico ECS do Grafana
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  GrafanaTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: grafana-stack
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: grafana
          Image: !Ref GrafanaImage
          Essential: true
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/monitoring
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: grafana
          Environment:
            - Name: GF_INSTALL_PLUGINS
              Value: aws-datasource-provisioner-app
          MountPoints:
            - SourceVolume: grafana-config
              ContainerPath: /etc/grafana
        - Name: tempo
          Image: !Ref TempoImage
          Essential: true
          PortMappings:
            - ContainerPort: 3200
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/monitoring
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: tempo
          MountPoints:
            - SourceVolume: tempo-config
              ContainerPath: /etc/tempo
        - Name: loki
          Image: !Ref LokiImage
          Essential: true
          PortMappings:
            - ContainerPort: 3100
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/monitoring
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: loki
          MountPoints:
            - SourceVolume: loki-config
              ContainerPath: /etc/loki
        - Name: prometheus
          Image: !Ref PrometheusImage
          Essential: true
          PortMappings:
            - ContainerPort: 9090
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/monitoring
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: prometheus
          MountPoints:
            - SourceVolume: prometheus-config
              ContainerPath: /etc/prometheus
      Volumes:
        - Name: grafana-config
          Host:
            SourcePath: /mnt/efs/grafana
        - Name: tempo-config
          Host:
            SourcePath: /mnt/efs/tempo
        - Name: loki-config
          Host:
            SourcePath: /mnt/efs/loki
        - Name: prometheus-config
          Host:
            SourcePath: /mnt/efs/prometheus

  GrafanaService:
    Type: AWS::ECS::Service
    DependsOn:
      - GrafanaTargetGroup
      - GrafanaListener
      - GrafanaLogGroup
    Properties:
      Cluster: !Ref ClusterName
      ServiceName: grafana-service
      TaskDefinition: !Ref GrafanaTaskDefinition
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !GetAtt GrafanaServiceSecurityGroup.GroupId
          Subnets: !Ref SubnetIds
      LoadBalancers:
        - ContainerName: grafana
          ContainerPort: 3000
          TargetGroupArn: !Ref GrafanaTargetGroup

  GrafanaLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub grafana-alb-${AWS::StackName}
      Scheme: internet-facing
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref GrafanaALBSecurityGroup
      Type: application

  GrafanaALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group para o ALB do Grafana
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  GrafanaTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub tg-${AWS::StackName}
      Protocol: HTTP
      Port: 3000
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher:
        HttpCode: 200-399

  GrafanaListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref GrafanaLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref GrafanaTargetGroup

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

Outputs:
  LoadBalancerDNSName:
    Description: DNS do Load Balancer para acessar o Grafana
    Value: !GetAtt GrafanaLoadBalancer.DNSName
