version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - yum update -y
      - yum install -y jq
      - pip install awscli

  pre_build:
    commands:
      - echo 'Iniciando a fase de pre_build...'
      - echo 'Buscando secrets do AWS Secrets Manager'
      - |
        SECRETS=$(aws secretsmanager get-secret-value --secret-id dev/grafana/config --query SecretString --output text)
        ADMIN_USER=$(echo $SECRETS | jq -r '.GRAFANA_ADMIN_USER')
        ADMIN_PASSWORD=$(echo $SECRETS | jq -r '.GRAFANA_ADMIN_PASSWD')
      - echo 'Substituindo credenciais no grafana.ini'
      - sed -i "s/ADMINUSER/${ADMIN_USER}/g" devops/Applications/Grafana/grafana.ini
      - sed -i "s/ADMINPASSWD/${ADMIN_PASSWORD}/g" devops/Applications/Grafana/grafana.ini
      - echo 'Logging in to Amazon ECR...'
      - $(aws ecr get-login --no-include-email --region us-east-2)

  build:
    commands:
      - echo 'Iniciando o build...'
      - echo 'Building Docker images...'
      - docker build -t 975050172141.dkr.ecr.us-east-2.amazonaws.com/monitoring:tempo-latest ./devops/Applications/Tempo
      - docker build -t 975050172141.dkr.ecr.us-east-2.amazonaws.com/monitoring:prometheus-latest ./devops/Applications/Prometheus
      - docker build -t 975050172141.dkr.ecr.us-east-2.amazonaws.com/monitoring:loki-latest ./devops/Applications/Loki
      - docker build -t 975050172141.dkr.ecr.us-east-2.amazonaws.com/monitoring:grafana-latest ./devops/Applications/Grafana
      - echo 'Pushing Docker images to ECR...'
      - docker push 975050172141.dkr.ecr.us-east-2.amazonaws.com/monitoring:tempo-latest
      - docker push 975050172141.dkr.ecr.us-east-2.amazonaws.com/monitoring:prometheus-latest
      - docker push 975050172141.dkr.ecr.us-east-2.amazonaws.com/monitoring:loki-latest
      - docker push 975050172141.dkr.ecr.us-east-2.amazonaws.com/monitoring:grafana-latest

  post_build:
    commands:
      - echo 'Iniciando a fase de post_build...'
      - echo 'Validando o template CloudFormation'
      - aws cloudformation validate-template --template-body file://grafana-stack.yaml
      - echo 'Lendo parâmetros do arquivo parameters.json'
      - |
        PARAMETER_OVERRIDES=$(jq -r '.[] | "\(.ParameterKey)=\(.ParameterValue)"' devops/variables/parameters.json)
      - echo 'Fazendo deploy do stack CloudFormation'
      - |
        aws cloudformation deploy \
          --template-file grafana-stack.yaml \
          --stack-name grafana-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides $PARAMETER_OVERRIDES
      - echo 'Exibindo mudanças feitas no stack CloudFormation'
      - aws cloudformation describe-stack-events --stack-name grafana-stack --query 'StackEvents[?ResourceStatus==`UPDATE_COMPLETE`].{Resource:LogicalResourceId,Status:ResourceStatus,Reason:ResourceStatusReason}' --output table

artifacts:
  files:
    - grafana-stack.yaml
    - devops/variables/parameters.json
    - devops/Applications/Grafana/grafana.ini
    - devops/Applications/Tempo/tempo.yaml
    - devops/Applications/Loki/loki.yaml
    - devops/Applications/Prometheus/prometheus.yaml