version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - yum update -y
      - yum install -y jq

  build:
    commands:
      - echo "Iniciando o build..."
      - echo "Validando o template CloudFormation"
      - aws cloudformation validate-template --template-body file://grafana-stack.yaml
      - echo "Fazendo deploy do stack CloudFormation"
      - aws cloudformation deploy \
          --template-file grafana-stack.yaml \
          --stack-name grafana-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides $(cat devops/variables/parameters.json | jq -r '.[] | "\(.ParameterKey)=\(.ParameterValue)"')
artifacts:
  files:
    - grafana-stack.yaml
    - devops/variables/parameters.json
