version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - yum update -y
      - yum install -y jq
      - pip install awscli

  pre_build:
    commands:
      - echo 'Iniciando a fase de pre_build...'
      - echo 'Buscando secrets do AWS Secrets Manager'
      - |
        SECRETS=$(aws secretsmanager get-secret-value --secret-id dev/grafana/config --query SecretString --output text)
        ADMIN_USER=$(echo $SECRETS | jq -r '.GRAFANA_ADMIN_USER')
        ADMIN_PASSWORD=$(echo $SECRETS | jq -r '.GRAFANA_ADMIN_PASSWD')
      - echo 'Substituindo credenciais no grafana.ini'
      - sed -i "s/ADMINUSER/${ADMIN_USER}/g" devops/configurationFiles/grafana.ini
      - sed -i "s/ADMINPASSWD/${ADMIN_PASSWORD}/g" devops/configurationFiles/grafana.ini
      - echo 'Logging in to Amazon ECR...'
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)

  build:
    commands:
      - echo 'Iniciando o build...'
      - echo 'Building Docker images...'
      - docker build -t $ECR_REPO_URI:tempo-latest ./repos/gen-infrastructure-monitoring-grafana/devops/Dockerfiles/Tempo
      - docker build -t $ECR_REPO_URI:prometheus-latest ./repos/gen-infrastructure-monitoring-grafana/devops/Dockerfiles/Prometheus
      - docker build -t $ECR_REPO_URI:loki-latest ./repos/gen-infrastructure-monitoring-grafana/devops/Dockerfiles/Loki
      - docker build -t $ECR_REPO_URI:grafana-latest ./repos/gen-infrastructure-monitoring-grafana/devops/Dockerfiles/Grafana
      - echo 'Pushing Docker images to ECR...'
      - docker push $ECR_REPO_URI:tempo-latest
      - docker push $ECR_REPO_URI:prometheus-latest
      - docker push $ECR_REPO_URI:loki-latest
      - docker push $ECR_REPO_URI:grafana-latest

  post_build:
    commands:
      - echo 'Iniciando a fase de post_build...'
      - echo 'Copiando arquivos de configuração para o bucket S3...'
      - aws s3 cp devops/configurationFiles/grafana.ini s3://grafanadev-configs/grafana.ini
      - aws s3 cp devops/configurationFiles/loki.yaml s3://grafanadev-configs/loki.yaml
      - aws s3 cp devops/configurationFiles/tempo.yaml s3://grafanadev-configs/tempo.yaml
      - aws s3 cp devops/configurationFiles/prometheus.yaml s3://grafanadev-configs/prometheus.yaml
      - echo 'Validando o template CloudFormation'
      - aws cloudformation validate-template --template-body file://grafana-stack.yaml
      - echo 'Lendo parâmetros do arquivo parameters.json'
      - |
        PARAMETER_OVERRIDES=$(jq -r '.[] | "\(.ParameterKey)=\(.ParameterValue)"' devops/variables/parameters.json)
      - echo 'Fazendo deploy do stack CloudFormation'
      - |
        aws cloudformation deploy \
          --template-file grafana-stack.yaml \
          --stack-name grafana-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides $PARAMETER_OVERRIDES
      - echo 'Exibindo mudanças feitas no stack CloudFormation'
      - aws cloudformation describe-stack-events --stack-name grafana-stack --query 'StackEvents[?ResourceStatus==`UPDATE_COMPLETE`].{Resource:LogicalResourceId,Status:ResourceStatus,Reason:ResourceStatusReason}' --output table

artifacts:
  files:
    - grafana-stack.yaml
    - devops/variables/parameters.json
    - devops/configurationFiles/grafana.ini
    - devops/configurationFiles/tempo.yaml
    - devops/configurationFiles/loki.yaml
    - devops/configurationFiles/prometheus.yaml