AWSTemplateFormatVersion: 2010-09-09
Description: Create EFS File Systems and Mount Targets for Grafana, Tempo, Loki and Prometheus

Resources:
  GrafanaEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS

  TempoEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS

  LokiEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS

  PrometheusEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS

Outputs:
  GrafanaEFSFileSystemId:
    Description: ID of the Grafana EFS File System
    Value: !Ref GrafanaEFSFileSystem

  TempoEFSFileSystemId:
    Description: ID of the Tempo EFS File System
    Value: !Ref TempoEFSFileSystem

  LokiEFSFileSystemId:
    Description: ID of the Loki EFS File System
    Value: !Ref LokiEFSFileSystem

  PrometheusEFSFileSystemId:
    Description: ID of the Prometheus EFS File System
    Value: !Ref PrometheusEFSFileSystem