AWSTemplateFormatVersion: 2010-09-09
Description: Create EFS File Systems and Mount Targets for Grafana, Tempo, Loki and Prometheus

Resources:
  GrafanaEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS

  TempoEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS

  LokiEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS

  PrometheusEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS

  GrafanaEFSAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref GrafanaEFSFileSystem

  TempoEFSAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref TempoEFSFileSystem

  LokiEFSAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref LokiEFSFileSystem

  PrometheusEFSAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref PrometheusEFSFileSystem

Outputs:
  GrafanaEFSFileSystemId:
    Description: ID of the Grafana EFS File System
    Value: !Ref GrafanaEFSFileSystem

  TempoEFSFileSystemId:
    Description: ID of the Tempo EFS File System
    Value: !Ref TempoEFSFileSystem

  LokiEFSFileSystemId:
    Description: ID of the Loki EFS File System
    Value: !Ref LokiEFSFileSystem

  PrometheusEFSFileSystemId:
    Description: ID of the Prometheus EFS File System
    Value: !Ref PrometheusEFSFileSystem

  GrafanaEFSAccessPointId:
    Description: ID of the Grafana EFS Access Point
    Value: !Ref GrafanaEFSAccessPoint

  TempoEFSAccessPointId:
    Description: ID of the Tempo EFS Access Point
    Value: !Ref TempoEFSAccessPoint

  LokiEFSAccessPointId:
    Description: ID of the Loki EFS Access Point
    Value: !Ref LokiEFSAccessPoint

  PrometheusEFSAccessPointId:
    Description: ID of the Prometheus EFS Access Point
    Value: !Ref PrometheusEFSAccessPoint