server:
  http_listen_port: 3100
  grpc_listen_port: 3200

distributor:
  receivers:
    jaeger:
      protocols:
        grpc:
        thrift_binary:
        thrift_compact:
        thrift_http:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  wal:
    enabled: true
    dir: /var/tempo/wal

compactor:
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces

querier:
  frontend_worker:
    frontend_address: frontend:9095
  query_ingesters_within: 2h

frontend:
  address: 0.0.0.0:9095